version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_ADDR=${SERVER_ADDR}

  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    depends_on:
      - server
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_DEST_SERVER_ADDR=${CLIENT_DEST_SERVER_ADDR}
